- name: "{{ XDG_CONFIG_HOME }}/bash/bashrc will be sourced"
  become: true
  blockinfile:
    path: /etc/bash.bashrc
    block: "{{ lookup('ansible.builtin.file', 'bash.bashrc') }}"
    prepend_newline: yes
    validate: /bin/bash -n %s
  tags:
    - bash

- name: "{{ XDG_CONFIG_HOME }}/bash/bash_logout will be taken into account"
  become: true
  blockinfile:
    path: /etc/bash.bash.logout
    create: true
    block: "{{ lookup('ansible.builtin.file', 'bash.bash.logout') }}"
    prepend_newline: yes
    validate: /bin/bash -n %s
  tags:
    - bash

- name: "{{ XDG_CONFIG_HOME }}/bash directory exists"
  file:
    path: "{{ XDG_CONFIG_HOME }}/bash"
    state: directory
  tags:
    - profile

- name: No ~/.bashrc
  shell:
    cmd: mv "{{ ansible_env.HOME }}/.bashrc" "{{ XDG_CONFIG_HOME }}/bash/bashrc" || rm "{{ ansible_env.HOME }}/.bashrc"
    removes: "{{ ansible_env.HOME }}/.bashrc"
  tags:
    - bash

- name: No old references in bashrc
  replace:
    path: "{{ XDG_CONFIG_HOME }}/bash/bashrc"
    regexp: '\s~/\.bash'
    replace: ' ~/.config/bash/bash'
  when: lookup('file', '~/.bashrc', errors='ignore')


- name: No ~/.bash_aliases
  shell:
    cmd: mv "{{ ansible_env.HOME }}/.bash_aliases" "{{ XDG_CONFIG_HOME }}/bash/bash_aliases" || rm "{{ ansible_env.HOME }}/.bash_aliases"
    removes: "{{ ansible_env.HOME }}/.bash_aliases"
  tags:
    - bash

- name: No ~/.bash_logout
  shell:
    cmd: mv "{{ ansible_env.HOME }}/.bash_logout" "{{ XDG_CONFIG_HOME }}/bash/bash_logout" || rm "{{ ansible_env.HOME }}/.bash_logout"
    removes: "{{ ansible_env.HOME }}/.bash_logout"
  tags:
    - bash
