- name: Package is installed
  become: true
  apt:
    name:
      - gpg
      - yadm
    state: present
    update_cache: true
    cache_valid_time: "{{ 60*60*24*7 }}"  # 1 week
  tags:
    - install
    - yadm

- name: Dotfiles repository is present
  environment:
    GIT_TERMINAL_PROMPT: 0
  shell:
    cmd: "{{ yadm_cmd }} clone {{ yadm_dotfiles_repo }} --no-bootstrap && {{ yadm_cmd }} checkout -f"
    creates: "{{ yadm_git_path }}"
  tags:
    - install
    - yadm

- name: Pull is done throught HTTPS
  community.general.git_config:
    repo: "{{ yadm_git_path }}"
    name: remote.origin.url
    value: "{{ yadm_dotfiles_repo | regex_replace('git@github.com:', '^https://github.com/') }}"
    scope: local
  tags:
    - install
    - yadm

- name: Push is done throught SSH
  community.general.git_config:
    repo: "{{ yadm_git_path }}"
    name: remote.origin.pushurl
    value: "{{ yadm_dotfiles_repo | regex_replace('^https://github.com/', 'git@github.com:') }}"
    scope: local
  tags:
    - install
    - yadm

- name: Gitconfig include is linked
  git_config:
    repo: "{{ yadm_git_path }}"
    name: include.path
    value: "{{ yadm_config_path }}/gitconfig"
    scope: local
  tags:
    - yadm
    - config

- name: Sparse checkout is enabled
  git_config:
    repo: "{{ yadm_git_path }}"
    name: core.sparseCheckout
    value: true
    scope: local
  tags:
    - yadm
    - config

- name: Sparse checkout files are configured
  copy:
    src: sparse-checkout
    dest: "{{ yadm_git_path }}/info/sparse-checkout"
  tags:
    - yadm
    - config

- name: Sparse checkout is applied
  environment:
    GIT_TERMINAL_PROMPT: 0
  command:
    chdir: "{{ yadm_git_worktree }}"
    cmd: "{{ yadm_cmd }} sparse-checkout reapply"
    removes: ".github/"
  tags:
    - yadm
    - config

- name: Dotfiles repository is updated
  environment:
    GIT_TERMINAL_PROMPT: 0
  command:
    cmd: "{{ yadm_cmd }} pull"
  register: yadm_pulled
  changed_when: not yadm_pulled.stdout is search("Already up to date")
  tags:
    - update
    - yadm
