- name: Dependencies are installed
  become: true
  apt:
    name: "{{ nvim_dependencies }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ 60*60*24*7 }}"
  tags:
    - install
    - dependencies
    - nvim

- name: Check installed nvim version
  shell:
    cmd: /opt/nvim/bin/nvim --version || true | head -n 1 | awk '{print $2}'
  register: nvim_version
  changed_when: false
  tags:
    - install
    - update
    - nvim

- name: Check latest nvim release
  uri:
    url: https://api.github.com/repos/neovim/neovim/releases/latest
    return_content: true
  register: nvim_release
  changed_when: false
  tags:
    - install
    - update
    - nvim

- name: NVIM stable is installed
  block:
    - name: Download release for x86_64
      include_tasks: release.yml
      when: ansible_architecture == "x86_64"

    - name: Build release for arm64
      include_tasks: build.yml
      when: ansible_architecture == "aarch64"

  when: nvim_release.json["tag_name"] != nvim_version.stdout
  become: true
  tags:
    - install
    - update
    - nvim

- name: Needed plugins are installed
  command:
    cmd: "/opt/nvim/bin/nvim --headless '+qa'"
  register: lazy_bootstraped
  changed_when: lazy_bootstraped.stdout | length > 0
  tags:
    - install
    - nvim
    - update
    - config

- name: Plugins are up to date
  command:
    cmd: "/opt/nvim/bin/nvim --headless '+Lazy! sync' '+qa'"
  register: lazy_updated
  changed_when: lazy_updated.stdout_lines | reject('search', 'checkout') | reject('search', 'fetch') | reject('search', 'status') | length > 0
  tags:
    - install
    - nvim
    - update
    - config

- name: Treesitter parsers are installed
  command:
    cmd: "/opt/nvim/bin/nvim --headless '+Lazy load nvim-treesitter' '+qa'"
  register: lazy_bootstraped
  changed_when: lazy_bootstraped.stdout | length > 0
  tags:
    - install
    - nvim
    - update
    - config

- name: LSPs are installed from mason (not working?)
  command:
    cmd: "/opt/nvim/bin/nvim --headless '+Lazy load nvim-lspconfig' '+qa'"
  register: lazy_bootstraped
  changed_when: lazy_bootstraped.stdout | length > 0
  tags:
    - install
    - nvim
    - update
    - config
